chain = "mainnet"
log-level = "INFO"
datadir = "/var/lib/bor/data"
# ancient = ""
keystore = "/var/lib/bor/keystore"
syncmode = "full"
# gcmode = "full"
 snapshot = true
# "bor.logs" = false
ethstats = "ID:mainnet@bor-mainnet.vitwit.com:3000"

["eth.requiredblocks"]

[p2p]
	 maxpeers = 5
#   maxpendpeers = 50
#   bind = "0.0.0.0"
  port = 30303
  nodiscover = true
#   nat = "any"
  [p2p.discovery]
#     v5disc = false
	 bootnodes = [ "Bootnodes" ]
#     bootnodesv4 = []
#     bootnodesv5 = []
    static-nodes =  [ "Static Nodes" ]
    trusted-nodes = [ "Trustned Nodes" ]
#     dns = []

[heimdall]
#   url = "http://localhost:1317"
#   "bor.without" = false

[txpool]
#   locals = []
  nolocals = true
#   journal = "transactions.rlp"
#   rejournal = "1h0m0s"
  pricelimit = 30000000000
#   pricebump = 10
  accountslots = 16
  globalslots = 131072
  accountqueue = 64
  globalqueue = 131072
  lifetime = "1h30m0s"

[miner]
  mine = true
  etherbase = "ADDRESS"
#   extradata = ""
  gaslimit = 30000000
  gasprice = "30000000000"

[jsonrpc]
#   ipcdisable = false
  ipcpath = "/var/lib/bor/bor.ipc"
#   gascap = 50000000
#   txfeecap = 5.0
  [jsonrpc.http]
    enabled = true
    port = 8545
#     prefix = ""
    host = "0.0.0.0"
	 api = ["eth", "net", "web3", "txpool", "debug", "bor"]
    vhosts = ["*"]
    corsdomain = ["*"]
  [jsonrpc.ws]
     enabled = false
#     port = 8546
#     prefix = ""
#     host = "localhost"
#     api = ["net", "web3"]
#     origins = ["localhost"]
  [jsonrpc.graphql]
#     enabled = false
#     port = 0
#     prefix = ""
#     host = ""
#     vhosts = ["localhost"]
#     corsdomain = ["localhost"]
  [jsonrpc.timeouts]
    read = "30s"
    write = "30s"
    idle = "2m0s"

[gpo]
#   blocks = 20
#   percentile = 60
#   maxprice = "5000000000000"
#   ignoreprice = "2"

[telemetry]
  metrics = true
  expensive = true
  prometheus-addr = "0.0.0.0:7071"
# opencollector-endpoint = ""
 #     cloud = "aws"
 #     host = "anonymous-91"
 #     ip = "34.217.171.158"
 #     region = "us-east-2"
 #     type = "validators"

[cache]
 cache = 4096
#   gc = 25
#   snapshot = 10
#   database = 50
#   trie = 15
#   journal = "triecache"
#   rejournal = "1h0m0s"
#   noprefetch = false
#   preimages = false
#   txlookuplimit = 2350000
  timeout = "1h0m0s"

[accounts]
  unlock = ["ADDRESS"]
  password = "/var/lib/bor/password.txt"
  allow-insecure-unlock = true
#   lightkdf = false
#   disable-bor-wallet = true

[grpc]
#   addr = ":3131"

[developer]
#   dev = false
#   period = 0
